extensions:
  workfront/ui/1:
    $include: src/workfront-ui-1/ext.config.yaml
    runtimeManifest:
      packages:
        ext2:
          license: Apache-2.0
          actions:
            publish-events:
              function: src/workfront-ui-1/actions/publish-events/index.js
              web: 'yes'
              runtime: nodejs:18
              inputs:
                LOG_LEVEL: debug
                apiKey: $SERVICE_API_KEY
              annotations:
                require-adobe-auth: true
                final: true
            create:
              function: src/workfront-ui-1/actions/create/index.js
              web: 'yes'
              runtime: nodejs:18
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: true
                final: true
